[FEAT] Jwt, Passport를 이용한 토큰 발급 및 jwt-auth.gaurd 정의
TEAM-README/Readme-Server pull request #33
Opened 2022-05-22 16:07 UTC by eunji8784

## Issue Ticket 🎫

- closed #32 

<br>

## Describe your changes 🧾

- POST /user/auth/access-token (임시 url) 통해 토큰 발급
- 리프레시 토큰, 소셜 로그인 구현 필요
- 닉네임 수정 API에 토큰 인증 추가
- Postman에서 토큰 넣을 때 Authorization -> Type: Bearer Token으로 해서 넣으면 됩니다.

__POST /user/auth/access-token__

<img width="807" alt="스크린샷 2022-05-23 오전 12 49 19" src="https://user-images.githubusercontent.com/70746467/169704248-37fef888-4fba-43a3-ae51-4d2bca8795e8.png">

__token validation__
<img width="355" alt="스크린샷 2022-05-22 오후 11 16 13" src="https://user-images.githubusercontent.com/70746467/169704450-6567e3db-098c-4897-8425-e4f7d5694646.png">
<img width="384" alt="스크린샷 2022-05-22 오후 11 16 27" src="https://user-images.githubusercontent.com/70746467/169704459-fb426102-6f24-41ea-8b4c-abcfa5c1dea7.png">
<img width="386" alt="스크린샷 2022-05-22 오후 11 17 09" src="https://user-images.githubusercontent.com/70746467/169704462-45e244a8-ceaf-48e4-99b6-17fcbbf0775f.png">

<br>

2022-05-22 17:23 UTC, youngkwon02 approved these changes
오왕.. 혼자 하느라 고생했어 은지야!!
남은 작업 공유해주면 호다닥 해치워버리자!

2022-05-23 08:16 UTC, junguksim requested changes

2022-05-23 08:16 UTC, junguksim commented on src/auth/auth.service.ts
> +        message: '존재하지 않는 닉네임입니다.',
존재하지 않는 유저입니다 가 되어야하지 않을까?

2022-05-23 08:16 UTC, junguksim commented on src/auth/guard/jwt-auth.guard.ts
> +    if (authorization === undefined) {
if(!authorization) 으로 해도 될듯

2022-05-23 14:38 UTC, eunji8784 commented on src/auth/auth.service.ts
> +        message: '존재하지 않는 닉네임입니다.',
수정하겠습니다~!

2022-05-23 14:38 UTC, eunji8784 commented on src/auth/guard/jwt-auth.guard.ts
> +    if (authorization === undefined) {
그렇네요! 이것도 수정하겠습니다~!

2022-05-23 14:46 UTC, junguksim approved these changes

2022-05-23 14:50 UTC, eunji8784 commented
#29, #31 pr 머지하고 나서 컨플릭트 해결하겠습니답!

2022-05-23 14:50 UTC, eunji8784 commented
#29, #31 pr 머지하고 나서 컨플릭트 해결하겠습니답!

2022-05-23 15:15 UTC, merged